name: event_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  loading_overlay: ^0.4.2
  rflutter_alert: ^2.0.7
  flutter_native_splash: ^2.3.10
  flutter_screenutil: ^5.9.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.6.2
  shared_preferences: ^2.2.3
  intl: ^0.20.2
  open_filex: ^4.6.0
  file_picker: ^8.3.5
  google_maps_flutter: ^2.6.1
  url_launcher: ^6.2.6
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  image_picker: ^1.1.0
  location: ^8.0.0
  firebase_storage: ^12.4.1
  permission_handler: ^11.3.1
  flutter_image_compress: ^2.2.0
  progress_dialog_null_safe: ^3.0.0
  provider: ^6.1.2
  carousel_slider: ^5.0.0
  firebase_messaging: ^15.2.1
  flutter_chat_ui: ^1.6.15
  http: ^1.2.1
  flutter_local_notifications: ^18.0.1
  rxdart_ext: ^0.2.9
  rxdart: ^0.27.5
  path_provider: ^2.1.3
  custom_rating_bar: ^3.0.0
  loading_animation_widget: ^1.2.1
  persistent_bottom_nav_bar: ^6.2.1
  google_places_flutter: ^2.0.8
  flutter_stripe: ^11.4.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/.env
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Bold.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf